
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: auth_user
    password: auth_pass

iam:
  base-url: http://iam-server:9083
  internal-token: dev-internal-token

auth:
  signing:
    key-path: /run/secrets/auth-signing-key.jwk

logging:
  level:
    org.springframework.security: INFO
