
spring:
  datasource:
    url: jdbc:postgresql://${IAM_DB_HOST:postgres}:5432/iamdb
    username: ${IAM_DB_USER:iam_user}
    password: ${IAM_DB_PASS:iam_pass}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER:http://localhost:9081}
          jwk-set-uri: ${AUTH_JWKS_URI:http://auth-server:9081/oauth2/jwks}
